city: Berlin
timezone: Europe/Berlin
stations:
  - id: be_001
    name: Berlin-Center
    latitude: 52.5200
    longitude: 13.4050
  - id: be_002
    name: Berlin-North
    latitude: 52.55
    longitude: 13.40
holidays: de
