name: Hamburg
slug: hamburg
timezone: Europe/Berlin
providers: [cams, aurora, gefs_aerosol]
holidays_calendar: DE-HH   # Hamburg city-state
bounds:
  lat_min: 53.3
  lat_max: 53.7
  lon_min: 9.7
  lon_max: 10.3
stations:
  - id: de_hh_001
    name: Urban background (example)