city: Munich
timezone: Europe/Berlin
stations:
  - id: mu_001
    name: Munich-Center
    latitude: 48.1351
    longitude: 11.5820
  - id: mu_002
    name: Munich-North
    latitude: 48.17
    longitude: 11.60
holidays: de
