name: Munich
slug: munich
timezone: Europe/Berlin
providers: [cams, aurora, gefs_aerosol]
holidays_calendar: DE-BY   # Bavaria
bounds:
  lat_min: 48.0
  lat_max: 48.3
  lon_min: 11.4
  lon_max: 11.8
stations:
  - id: de_by_muc_001
    name: Urban background (example)
