name: pm25-berlin CI

on:
  push:
    branches: [ main ]
    paths:
      - 'pm25-berlin/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'pm25-berlin/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: pm25-berlin
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Bootstrap environment
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
      - name: List repo files
        run: ls -la
