name: pm25-berlin CI

on:
  push:
    branches: [ main ]
    paths:
      - 'pm25-berlin/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'pm25-berlin/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: pm25-berlin
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Bootstrap environment
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: Create .env from example
        run: cp .env.example .env

      - name: Stage 0 smoke test (Python)
        run: |
          source .venv/bin/activate
          python - <<'PY'
          import os, sys
          from pm25_forecast import env  # loads .env
          keys = ["DATA_ROOT", "MODELS_ROOT"]
          missing = []
          for k in keys:
            v = os.getenv(k)
            print(f"{k}: {v}")
            if not v or v.strip().lower() in {"", "none", "null"}:
              missing.append(k)
          if missing:
            print("ERROR: Missing or empty:", ", ".join(missing))
            sys.exit(1)
          print("Smoke test OK.")
          PY
