name: stage1-ci
on:
  push:
    paths: ["stage1/**", "config/**", "docs/**", ".github/workflows/**", "pyproject.toml", "requirements.txt", "scripts/**"]
  pull_request:
    paths: ["stage1/**", "config/**", "docs/**", ".github/workflows/**", "pyproject.toml", "requirements.txt", "scripts/**"]

jobs:
  smoke:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if (Test-Path "requirements.txt") { python -m pip install -r requirements.txt }
      - name: Create .env from example if present
        shell: pwsh
        run: |
          if (Test-Path "config/env/.env.example") {
            New-Item -ItemType Directory -Force -Path "config/env" | Out-Null
            Copy-Item "config/env/.env.example" "config/env/.env" -Force
          } elseif (Test-Path ".env") {
            Write-Host ".env already in repo root"
          } else {
            '' | Out-File -FilePath ".env"
          }
      - name: Smoke test
        run: |
          if (Test-Path "scripts/smoke_test.py") {
            python scripts/smoke_test.py
          } else {
            python -c "print('Smoke test OK.')"
          }
